// AUTO-GENERATED by scripts/generate-barrels.ts — DO NOT EDIT BY HAND.
// Phase-1 monorepo bridge: re-exports @swarm/swarm-templates's live src/ sources so it is
// importable by package name before any files move. Regenerate after editing
// packages.map.json:  bun scripts/generate-barrels.ts

export * from "../../templates/schema";
