import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { type AmpMode, type AmpModelSelection, resolveAmpModel } from "../utils/amp-models";
import {
  CONTEXT_FORMULA,
  clampContextPercent,
  computeContextUsedUnified,
} from "../utils/context-window";
import { swarmRuntimeInstanceId } from "../utils/multi-runtime";
import {
  detachedProcessGroup,
  listDescendantPids,
  registerProcessGroup,
  terminatePids,
  terminateProcessGroup,
  terminateProcessTree,
} from "../utils/process-group";
import { registerVolatileSecret, scrubSecrets } from "../utils/secret-scrubber";
import { resolveSlashSkillPrompt } from "./codex-skill-resolver";
import { applyReasoningEffort, type ReasoningEffort } from "./reasoning-effort";
import type {
  CostData,
  CostModelUsage,
  CredStatus,
  ProviderAdapter,
  ProviderEvent,
  ProviderResult,
  ProviderSession,
  ProviderSessionConfig,
  ProviderTraits,
  SteerDelivery,
  SteerDeliveryResult,
} from "./types";

/**
 * The pinned Amp CLI. Amp ships several releases a day and auto-updates by
 * default; the image installs exactly this version and the per-task settings
 * set `amp.updates.mode: "disabled"`. Bump it deliberately, with a live run.
 */
export const AMP_PACKAGE = "@ampcode/cli@0.0.1791187719-g319a37";

/** MCP server name. Amp exposes its tools as `agent_swarm` / `store_progress` (dashes become underscores). */
const AMP_MCP_SERVER_NAME = "agent-swarm";
/** Key of the per-task plugin mode that carries the swarm system prompt and any model pin. */
const AMP_PLUGIN_MODE_KEY = "agent-swarm";
/** Live test and thread export budgets. A missing key can make Amp wait instead of failing. */
const AMP_LIVE_TEST_TIMEOUT_MS = 5_000;
const AMP_EXPORT_TIMEOUT_MS = 20_000;
const AMP_EXPORT_RETRY_MS = 3_000;
const AMP_EXPORT_RETRIES = 1;
/** After stdin closes, `result` follows at once; this only guards a wedged process. */
const AMP_EXIT_AFTER_INPUT_MS = 60_000;
/** An unterminated stderr run longer than this is cut at a space, so a token is never split. */
const AMP_STDERR_RECORD_MAX = 16_384;
/** A queued steering message is echoed back as a `user` event when its turn starts. */
const AMP_QUEUED_ECHO_MS = 30_000;

export function checkAmpCredentials(env: Record<string, string | undefined>): CredStatus {
  return env.AMP_API_KEY?.trim()
    ? { ready: true, missing: [], satisfiedBy: "env" }
    : {
        ready: false,
        missing: ["AMP_API_KEY"],
        hint: "Set AMP_API_KEY (an access token from ampcode.com/settings) for amp.",
      };
}

/** The amp executable: `AMP_BINARY` (a trusted preinstalled path), else `amp` on PATH. */
export function resolveAmpBinary(env: Record<string, string | undefined>): string | null {
  return env.AMP_BINARY || Bun.which("amp", { PATH: env.PATH }) || null;
}

/** Amp's plugin agents take `none` where our normalized enum says `off`. */
function ampEffort(level: ReasoningEffort): string {
  return level === "off" ? "none" : level;
}

/**
 * The per-task plugin: one agent mode that extends a built-in mode, appends the
 * swarm system prompt as `instructions`, and optionally pins a model and an
 * effort. Amp has no system-prompt flag, so this is the supported route (live
 * verified: the instructions reach the model). The values are a JSON literal,
 * never code, so a prompt cannot break out of the string.
 */
export function buildAmpPlugin(options: {
  baseMode: AmpMode;
  instructions: string;
  pin?: string;
  reasoningEffort?: string | null;
}): string {
  const config = JSON.stringify({
    baseMode: options.baseMode,
    instructions: options.instructions,
    model: options.pin ?? null,
    reasoningEffort: options.reasoningEffort ?? null,
  });
  return `// @amp-agent-mode key=${AMP_PLUGIN_MODE_KEY} label=Agent Swarm
// Generated by the agent-swarm worker for one task. Do not edit.
export const description = "Agent Swarm worker mode generated for one task.";

const CONFIG = ${config};

export default function (amp: any) {
	amp.registerAgentMode({
		key: ${JSON.stringify(AMP_PLUGIN_MODE_KEY)},
		label: "Agent Swarm",
		agent: amp.createAgent({
			extends: CONFIG.baseMode,
			...(CONFIG.instructions ? { instructions: CONFIG.instructions } : {}),
			...(CONFIG.model ? { model: CONFIG.model } : {}),
			...(CONFIG.reasoningEffort ? { reasoningEffort: CONFIG.reasoningEffort } : {}),
			display: { label: "Agent Swarm" },
		}).definition,
	});
}
`;
}

/**
 * Per-task Amp settings. Updates are off (the image pins the binary), commits
 * carry no Amp co-author or thread trailer (they would stamp every swarm
 * commit), and prompts are off: the worker container is the sandbox, as it is
 * for codex and dsh.
 */
function buildAmpSettings(): Record<string, unknown> {
  return {
    "amp.updates.mode": "disabled",
    "amp.notifications.enabled": false,
    "amp.notifications.system.enabled": false,
    "amp.git.commit.coauthor.enabled": false,
    "amp.git.commit.ampThread.enabled": false,
    "amp.dangerouslyAllowAll": true,
  };
}

function swarmMcpConfig(config: ProviderSessionConfig): Record<string, unknown> {
  const runtimeInstanceId = swarmRuntimeInstanceId();
  return {
    [AMP_MCP_SERVER_NAME]: {
      url: `${config.apiUrl}/mcp`,
      headers: {
        Authorization: `Bearer ${config.apiKey}`,
        "X-Agent-ID": config.agentId,
        "X-Source-Task-Id": config.taskId,
        ...(config.contextKey ? { "X-Context-Key": config.contextKey } : {}),
        ...(runtimeInstanceId ? { "X-Runtime-Instance-ID": runtimeInstanceId } : {}),
      },
    },
  };
}

// ─── Live test ───────────────────────────────────────────────────────────────

export interface AmpLiveTestResult {
  ok: boolean;
  error?: string;
}

/**
 * `amp usage` reads the credit balance and runs no inference. It exits 1 with
 * "Invalid or missing API key" for a bad key. The output of a good key names
 * the account holder, so it is never returned.
 */
export async function liveTestAmpCredentials(
  env: Record<string, string | undefined>,
  timeoutMs: number = AMP_LIVE_TEST_TIMEOUT_MS,
): Promise<AmpLiveTestResult> {
  const binary = resolveAmpBinary(env);
  if (!binary) {
    return {
      ok: false,
      error: `amp CLI not found. Install ${AMP_PACKAGE} during image provisioning or set AMP_BINARY to a trusted executable.`,
    };
  }
  // The key may exist only in this env, where the scrubber cannot see it, and
  // `amp usage` can echo it in an error.
  const apiKey = env.AMP_API_KEY?.trim();
  if (apiKey) registerVolatileSecret(apiKey, "AMP_API_KEY");
  // A clean config dir keeps a stored `amp login` from masking a bad AMP_API_KEY.
  const configHome = await mkdtemp(join(tmpdir(), "swarm-amp-live-"));
  try {
    const proc = registerProcessGroup(
      Bun.spawn([binary, "usage"], {
        env: {
          ...(env as Record<string, string>),
          XDG_CONFIG_HOME: configHome,
          AMP_SETTINGS_FILE: join(configHome, "amp", "settings.json"),
        },
        stdin: "ignore",
        stdout: "pipe",
        stderr: "pipe",
        detached: detachedProcessGroup,
      }),
    );
    let timedOut = false;
    const timer = setTimeout(() => {
      timedOut = true;
      void terminateProcessGroup(proc.pid);
    }, timeoutMs);
    try {
      const [exitCode, stdout, stderr] = await Promise.all([
        proc.exited,
        new Response(proc.stdout).text(),
        new Response(proc.stderr).text(),
      ]);
      if (timedOut) return { ok: false, error: `amp usage timed out after ${timeoutMs}ms` };
      if (exitCode === 0) return { ok: true };
      const line =
        (stderr.trim() || stdout.trim()).split("\n")[0]?.replace(/^Error:\s*/, "") ||
        `amp usage exited ${exitCode}`;
      return { ok: false, error: scrubSecrets(line).slice(0, 300) };
    } finally {
      clearTimeout(timer);
    }
  } finally {
    await rm(configHome, { recursive: true, force: true });
  }
}

// ─── Thread export (model, tokens, context window) ───────────────────────────

export interface AmpThreadUsage {
  models: CostModelUsage[];
  /** Model of the most tokens: the one the session mostly ran on. */
  primaryModel?: string;
  /** Amp's effective input limit for that model, from the last request. */
  contextWindow?: number;
  contextUsedTokens?: number;
  lastOutputTokens?: number;
}

function count(value: unknown): number {
  return typeof value === "number" && Number.isFinite(value) && value > 0 ? value : 0;
}

/** Anthropic bills prompt-cache writes; every other vendor's cache-creation count is plain input. */
function billsCacheWrites(model: string): boolean {
  return /^(anthropic\/)?claude/i.test(model);
}

/**
 * The stream names no model, so the model and the per-request usage come from
 * `amp threads export <id>`. Per model, cache-creation tokens stay cache writes
 * for Anthropic and become input for everyone else: Amp reports uncached prompt
 * tokens as `cache_creation_input_tokens` on every vendor, and the pricing
 * table charges a missing cache-write rate as $0.
 *
 * Subagent threads (Task, oracle, finder) are separate Amp threads and are not
 * in the export, so their tokens are not counted.
 */
export function parseAmpThreadUsage(thread: unknown): AmpThreadUsage | undefined {
  const messages = (thread as { messages?: unknown })?.messages;
  if (!Array.isArray(messages)) return undefined;
  const byModel = new Map<string, CostModelUsage>();
  let last: Record<string, unknown> | undefined;
  for (const message of messages) {
    const usage = (message as { role?: string; usage?: Record<string, unknown> } | null)?.usage;
    if ((message as { role?: string } | null)?.role !== "assistant" || !usage) continue;
    const model = typeof usage.model === "string" && usage.model ? usage.model : undefined;
    if (!model) continue;
    const entry = byModel.get(model) ?? {
      model,
      inputTokens: 0,
      outputTokens: 0,
      cacheReadTokens: 0,
      cacheWriteTokens: 0,
    };
    const cacheCreation = count(usage.cacheCreationInputTokens);
    entry.inputTokens += count(usage.inputTokens);
    entry.outputTokens += count(usage.outputTokens);
    entry.cacheReadTokens += count(usage.cacheReadInputTokens);
    if (billsCacheWrites(model)) entry.cacheWriteTokens += cacheCreation;
    else entry.inputTokens += cacheCreation;
    byModel.set(model, entry);
    last = usage;
  }
  if (byModel.size === 0) return undefined;
  const models = [...byModel.values()];
  const total = (m: CostModelUsage) =>
    m.inputTokens + m.outputTokens + m.cacheReadTokens + m.cacheWriteTokens;
  const primaryModel = [...models].sort((a, b) => total(b) - total(a))[0]?.model;
  const window = count(last?.maxInputTokens);
  return {
    models,
    primaryModel,
    contextWindow: window || undefined,
    contextUsedTokens: last ? count(last.totalInputTokens) + count(last.outputTokens) : undefined,
    lastOutputTokens: last ? count(last.outputTokens) : undefined,
  };
}

// ─── Session ─────────────────────────────────────────────────────────────────

type AmpStdin = { write(value: string): unknown; flush?(): unknown; end(): unknown };

interface AmpContentBlock {
  type?: string;
  text?: string;
  id?: string;
  name?: string;
  input?: unknown;
  tool_use_id?: string;
  content?: unknown;
}

interface AmpStreamEvent {
  type?: string;
  subtype?: string;
  session_id?: string;
  parent_tool_use_id?: string | null;
  mcp_servers?: { name?: string; status?: string }[];
  message?: {
    content?: AmpContentBlock[] | string;
    stop_reason?: string | null;
    usage?: {
      input_tokens?: number;
      output_tokens?: number;
      cache_read_input_tokens?: number;
      cache_creation_input_tokens?: number;
    };
  };
  is_error?: boolean;
  result?: string;
  num_turns?: number;
  duration_ms?: number;
}

function userMessage(text: string): string {
  return `${JSON.stringify({
    type: "user",
    message: { role: "user", content: [{ type: "text", text }] },
  })}\n`;
}

interface AmpRun {
  selection: AmpModelSelection;
  reasoningEffort: ReasoningEffort | null;
  taskId: string;
  agentId: string;
  binary: string;
  cwd: string;
  env: Record<string, string>;
  exitAfterInputMs: number;
}

class AmpSession implements ProviderSession {
  sessionId: string | undefined;
  readonly deliverSteering: (delivery: SteerDelivery) => Promise<SteerDeliveryResult>;
  private listeners: ((event: ProviderEvent) => void)[] = [];
  private pending: ProviderEvent[] = [];
  private output: string | undefined;
  private lastAssistantText = "";
  private failure: string | undefined;
  private stderr = "";
  private aborted = false;
  private completion: Promise<ProviderResult>;
  private readonly startedAt = Date.now();
  private result: AmpStreamEvent | undefined;
  private toolNames = new Map<string, string>();
  /** Tokens straight from the stream; the model-aware split comes from the export. */
  private tokens = { input: 0, output: 0, cacheRead: 0, cacheCreation: 0 };
  /** User messages written to stdin that Amp has not started yet (it echoes each as its turn begins). */
  private unechoed: string[] = [];
  private inputClosed = false;
  private echoWatchdog: ReturnType<typeof setTimeout> | undefined;
  private exitWatchdog: ReturnType<typeof setTimeout> | undefined;
  private termination: Promise<void> | undefined;
  /** Descendants seen while amp was alive, swept after a clean exit (see `captureDescendants`). */
  private descendants = new Set<number>();
  private captures: Promise<void>[] = [];

  constructor(
    private proc: Bun.Subprocess<"pipe", "pipe", "pipe">,
    private directory: string,
    prompt: string,
    private run: AmpRun,
  ) {
    this.emit({
      type: "raw_log",
      content: JSON.stringify({
        type: "system",
        subtype: "model.selected",
        provider: "amp",
        // Amp's stream does not name the model; this is what the adapter asked for.
        model: run.selection.model,
        mode: run.selection.baseMode,
        ...(run.reasoningEffort ? { reasoningEffort: run.reasoningEffort } : {}),
      }),
    });
    this.deliverSteering = async ({ text }) => {
      if (this.inputClosed || this.aborted) {
        return { delivered: false, reason: "Amp is no longer reading input (the turn has ended)" };
      }
      try {
        await this.writeInput(text);
        return { delivered: true, mode: "queue" };
      } catch (error) {
        this.endInput();
        return { delivered: false, reason: `Amp stdin write failed: ${String(error)}` };
      }
    };
    this.completion = this.runSession(prompt);
  }

  onEvent(listener: (event: ProviderEvent) => void): void {
    this.listeners.push(listener);
    for (const event of this.pending.splice(0)) listener(event);
  }

  private emit(event: ProviderEvent): void {
    if (this.listeners.length === 0) this.pending.push(event);
    else for (const listener of this.listeners) listener(event);
  }

  private get stdin(): AmpStdin {
    return this.proc.stdin as unknown as AmpStdin;
  }

  private async writeInput(text: string): Promise<void> {
    this.unechoed.push(text.trim());
    await this.stdin.write(userMessage(text));
    await this.stdin.flush?.();
  }

  /**
   * In `--stream-json-input` mode Amp keeps reading until EOF and only then
   * emits `result` and exits, so the adapter ends input at the turn boundary.
   * A message written during a turn queues behind it (verified live).
   */
  private endInput(): void {
    if (this.inputClosed) return;
    this.inputClosed = true;
    clearTimeout(this.echoWatchdog);
    // EOF makes amp finish and exit, so the tree is read first.
    void this.captureDescendants().finally(() => {
      try {
        void Promise.resolve(this.stdin.end()).catch(() => {});
      } catch {
        // The child may already have exited.
      }
    });
    this.exitWatchdog = setTimeout(() => {
      if (!this.failure) this.failure = "amp did not exit after its turn ended";
      void this.terminate();
    }, this.run.exitAfterInputMs);
  }

  /**
   * Stop amp and every descendant. Amp's shell tool starts commands in their
   * own session, so a group kill misses them, and once amp is gone they are
   * reparented and unfindable: every stop goes through here while amp is alive,
   * and the session settles only after it finishes.
   */
  private terminate(): Promise<void> {
    this.termination ??= terminateProcessTree(this.proc.pid);
    return this.termination;
  }

  /**
   * A successful amp exits on its own, and a command its shell tool left
   * running sits in a session of its own: the group cleanup misses it, and
   * once amp is gone it is reparented and unfindable. So the tree is read
   * while amp is alive (at end of input and again at `result`) and the
   * survivors are stopped after amp exits.
   */
  private captureDescendants(): Promise<void> {
    const capture = listDescendantPids(this.proc.pid)
      .then((pids) => {
        for (const pid of pids) this.descendants.add(pid);
      })
      .catch(() => {});
    this.captures.push(capture);
    return capture;
  }

  /** A top-level assistant message with no tool call ends the turn. */
  private onTurnEnd(): void {
    if (this.inputClosed) return;
    if (this.unechoed.length === 0) {
      this.endInput();
      return;
    }
    // A queued message is about to start another turn; if Amp never echoes it, stop waiting.
    clearTimeout(this.echoWatchdog);
    this.echoWatchdog = setTimeout(() => this.endInput(), AMP_QUEUED_ECHO_MS);
  }

  private consumeLine(line: string): void {
    if (!line.trim()) return;
    const clean = scrubSecrets(line);
    this.emit({ type: "raw_log", content: clean });
    let event: AmpStreamEvent;
    try {
      event = JSON.parse(clean);
    } catch {
      return; // Amp may print a plain-text warning; the raw line is already logged.
    }
    if (event.session_id && !this.sessionId) {
      this.sessionId = event.session_id;
      this.emit({ type: "session_init", sessionId: event.session_id, provider: "amp" });
    }
    switch (event.type) {
      case "system":
        if (event.subtype === "init") this.checkMcp(event);
        break;
      case "assistant":
        this.onAssistant(event);
        break;
      case "user":
        this.onUser(event);
        break;
      case "result":
        this.result = event;
        void this.captureDescendants();
        if (typeof event.result === "string") this.output = event.result;
        break;
    }
  }

  /**
   * Never run a worker without the swarm tools: it could not report progress.
   * Amp can emit `init` before the connection settles (measured: a server that
   * answered after 3s was still `connecting`), so an unsettled status passes;
   * a refused connection already reads `reconnecting` and fails.
   */
  private checkMcp(event: AmpStreamEvent): void {
    const server = event.mcp_servers?.find((s) => s.name === AMP_MCP_SERVER_NAME);
    const status = server?.status;
    if (status === "connected" || status === "connecting" || status === "pending") return;
    this.failure = `amp could not connect to the swarm MCP server (${status ?? "not listed"})`;
    void this.terminate();
  }

  private onAssistant(event: AmpStreamEvent): void {
    const message = event.message;
    if (!message) return;
    const blocks = Array.isArray(message.content) ? message.content : [];
    const topLevel = !event.parent_tool_use_id;
    const text = blocks
      .filter((b) => b.type === "text" && typeof b.text === "string")
      .map((b) => b.text as string)
      .join("");
    if (text) {
      if (topLevel) this.lastAssistantText = text;
      this.emit({ type: "message", role: "assistant", content: text });
    }
    let calledTool = false;
    for (const block of blocks) {
      if (block.type !== "tool_use" || !block.name) continue;
      calledTool = true;
      const toolCallId = block.id ?? "";
      this.toolNames.set(toolCallId, block.name);
      this.emit({ type: "tool_start", toolCallId, toolName: block.name, args: block.input ?? {} });
    }
    const usage = message.usage;
    if (usage) {
      const input = count(usage.input_tokens);
      const output = count(usage.output_tokens);
      const cacheRead = count(usage.cache_read_input_tokens);
      const cacheCreation = count(usage.cache_creation_input_tokens);
      this.tokens.input += input;
      this.tokens.output += output;
      this.tokens.cacheRead += cacheRead;
      this.tokens.cacheCreation += cacheCreation;
      const used = computeContextUsedUnified({
        inputTokens: input,
        cacheReadTokens: cacheRead,
        cacheCreateTokens: cacheCreation,
        outputTokens: output,
      });
      // The window is not in the stream; the final snapshot after the export carries it.
      if (used > 0) this.emitContext(used, output, null);
    }
    if (topLevel && !calledTool && message.stop_reason !== "tool_use") this.onTurnEnd();
  }

  private onUser(event: AmpStreamEvent): void {
    const blocks = Array.isArray(event.message?.content) ? event.message.content : [];
    for (const block of blocks) {
      if (block.type === "tool_result") {
        const toolCallId = block.tool_use_id ?? "";
        const toolName = this.toolNames.get(toolCallId) ?? "tool";
        this.toolNames.delete(toolCallId);
        this.emit({ type: "tool_end", toolCallId, toolName, result: block.content });
      } else if (block.type === "text" && !event.parent_tool_use_id) {
        // Amp echoes each user message as its turn starts.
        const index = this.unechoed.indexOf((block.text ?? "").trim());
        if (index >= 0) this.unechoed.splice(index, 1);
        clearTimeout(this.echoWatchdog);
      }
    }
  }

  private emitContext(used: number, output: number, window: number | null): void {
    this.emit({
      type: "context_usage",
      contextUsedTokens: used,
      contextTotalTokens: window,
      contextPercent: window ? (clampContextPercent(used, window) ?? 0) : null,
      outputTokens: output,
      contextFormula: CONTEXT_FORMULA,
    });
  }

  private async readStdout(): Promise<void> {
    const decoder = new TextDecoder();
    let buffer = "";
    for await (const chunk of this.proc.stdout) {
      buffer += decoder.decode(chunk, { stream: true });
      let newline = buffer.indexOf("\n");
      while (newline >= 0) {
        this.consumeLine(buffer.slice(0, newline));
        buffer = buffer.slice(newline + 1);
        newline = buffer.indexOf("\n");
      }
    }
    this.consumeLine(buffer + decoder.decode());
  }

  /**
   * Stderr is scrubbed per complete record, never per pipe chunk: a chunk can
   * end inside a secret, and each half would pass the scrubber on its own.
   */
  private async readStderr(): Promise<void> {
    const decoder = new TextDecoder();
    let pending = "";
    for await (const chunk of this.proc.stderr) {
      pending += decoder.decode(chunk, { stream: true });
      const end = Math.max(pending.lastIndexOf("\n"), pending.lastIndexOf("\r"));
      if (end >= 0) {
        this.emitStderr(pending.slice(0, end + 1));
        pending = pending.slice(end + 1);
      }
      if (pending.length > AMP_STDERR_RECORD_MAX) {
        const cut = pending.lastIndexOf(" ") + 1 || pending.length;
        this.emitStderr(pending.slice(0, cut));
        pending = pending.slice(cut);
      }
    }
    this.emitStderr(pending + decoder.decode());
  }

  private emitStderr(text: string): void {
    if (!text) return;
    const content = scrubSecrets(text);
    this.stderr = (this.stderr + content).slice(-8000);
    this.emit({ type: "raw_stderr", content });
  }

  /**
   * `amp threads export`: the only place Amp names the model it ran. A thread
   * killed mid-run (cancel) can lag behind on the server, or never reach it
   * (about one cancel in three was still empty after three retries), so one retry
   * follows an empty export and the cost then falls back to stream tokens,
   * unpriced. A finished session is not retried.
   */
  private async exportUsage(): Promise<AmpThreadUsage | undefined> {
    let usage = await this.exportUsageOnce();
    for (let retry = 0; !usage && !this.result && retry < AMP_EXPORT_RETRIES; retry++) {
      await Bun.sleep(AMP_EXPORT_RETRY_MS);
      usage = await this.exportUsageOnce();
    }
    return usage;
  }

  private async exportUsageOnce(): Promise<AmpThreadUsage | undefined> {
    if (!this.sessionId) return undefined;
    try {
      const proc = registerProcessGroup(
        Bun.spawn([this.run.binary, "threads", "export", this.sessionId], {
          cwd: this.run.cwd,
          env: this.run.env,
          stdin: "ignore",
          stdout: "pipe",
          stderr: "ignore",
          detached: detachedProcessGroup,
        }),
      );
      const timer = setTimeout(() => void terminateProcessGroup(proc.pid), AMP_EXPORT_TIMEOUT_MS);
      try {
        const [exitCode, text] = await Promise.all([proc.exited, new Response(proc.stdout).text()]);
        if (exitCode !== 0) return undefined;
        return parseAmpThreadUsage(JSON.parse(text));
      } finally {
        clearTimeout(timer);
      }
    } catch {
      return undefined; // Cost is best-effort; the task result must not depend on it.
    }
  }

  private buildCost(isError: boolean, thread: AmpThreadUsage | undefined): CostData | undefined {
    if (!this.sessionId) return undefined;
    const t = this.tokens;
    const models = thread?.models;
    const sum = (pick: (m: CostModelUsage) => number) =>
      (models ?? []).reduce((total, m) => total + pick(m), 0);
    const hasStreamTokens = t.input + t.output + t.cacheRead + t.cacheCreation > 0;
    if (!models && !hasStreamTokens) return undefined;
    // Without the export the stream's raw counts go out under the requested
    // mode or pin, with no `models`, and the API settles the row unpriced.
    return {
      sessionId: this.sessionId,
      taskId: this.run.taskId,
      agentId: this.run.agentId,
      // Amp reports tokens, not money; the API prices them from the `amp` rows.
      totalCostUsd: 0,
      inputTokens: models ? sum((m) => m.inputTokens) : t.input,
      outputTokens: models ? sum((m) => m.outputTokens) : t.output,
      cacheReadTokens: models ? sum((m) => m.cacheReadTokens) : t.cacheRead,
      cacheWriteTokens: models ? sum((m) => m.cacheWriteTokens) : t.cacheCreation,
      ...(models ? { models } : {}),
      durationMs: this.result?.duration_ms ?? Date.now() - this.startedAt,
      numTurns: this.result?.num_turns ?? null,
      model: thread?.primaryModel ?? this.run.selection.model,
      isError,
      provider: "amp",
    };
  }

  private async runSession(prompt: string): Promise<ProviderResult> {
    try {
      const [exitCode] = await Promise.all([
        this.proc.exited,
        this.readStdout(),
        this.readStderr(),
        this.writeInput(prompt).catch((error) => {
          this.failure = `Amp stdin write failed: ${scrubSecrets(String(error))}`;
          this.endInput();
          void this.terminate();
        }),
      ]);
      clearTimeout(this.exitWatchdog);
      clearTimeout(this.echoWatchdog);
      await this.termination;
      if (!this.termination) {
        await Promise.all(this.captures);
        await terminatePids(this.descendants);
      }
      const resultFailed =
        this.result !== undefined && (this.result.is_error || this.result.subtype !== "success");
      const output = this.output ?? (this.lastAssistantText || undefined);
      const isError =
        this.aborted || exitCode !== 0 || !!this.failure || !this.result || resultFailed;
      const failureReason = isError
        ? this.aborted
          ? "amp session aborted"
          : this.failure ||
            (resultFailed ? this.result?.result : undefined) ||
            this.stderr.trim().split("\n").slice(-3).join("\n") ||
            `amp exited ${exitCode} without a result`
        : undefined;
      if (failureReason) this.emit({ type: "error", message: failureReason });
      const thread = await this.exportUsage();
      if (thread?.contextUsedTokens && thread.contextWindow) {
        this.emitContext(
          thread.contextUsedTokens,
          thread.lastOutputTokens ?? 0,
          thread.contextWindow,
        );
      }
      if (thread?.primaryModel) {
        this.emit({
          type: "raw_log",
          content: JSON.stringify({
            type: "system",
            subtype: "model.resolved",
            provider: "amp",
            model: thread.primaryModel,
            mode: this.run.selection.baseMode,
          }),
        });
      }
      const cost = this.buildCost(isError, thread);
      if (cost) this.emit({ type: "result", cost, output, isError });
      return {
        exitCode: isError ? exitCode || 1 : 0,
        sessionId: this.sessionId,
        cost,
        output,
        isError,
        failureReason,
        appliedReasoningEffort: this.run.reasoningEffort,
      };
    } catch (error) {
      await this.terminate();
      const failureReason = scrubSecrets(String(error));
      this.emit({ type: "error", message: failureReason });
      return {
        exitCode: 1,
        sessionId: this.sessionId,
        cost: this.buildCost(true, undefined),
        isError: true,
        failureReason,
      };
    } finally {
      await rm(this.directory, { recursive: true, force: true });
    }
  }

  waitForCompletion(): Promise<ProviderResult> {
    return this.completion;
  }

  async abort(): Promise<void> {
    this.aborted = true;
    this.endInput();
    await this.terminate();
  }
}

// ─── Adapter ─────────────────────────────────────────────────────────────────

export class AmpAdapter implements ProviderAdapter {
  readonly name = "amp";
  readonly traits: ProviderTraits = {
    hasMcp: true,
    // MCP tools sit behind Amp's own `tool_search` + `code_exec`. Exposing them
    // directly cost ~61k extra input tokens per turn for the 131 swarm tools
    // (98k vs 37k, measured), so the default is kept and the prompt explains it.
    hasToolSearch: true,
    // Amp reads ~/.claude/skills and ~/.agents/skills, where the swarm syncs skills.
    nativeSkillDiscovery: true,
    hasLocalEnvironment: true,
    // `--stream-json-input` queues a message until the running turn ends.
    steerModes: ["queue"],
  };

  constructor(private readonly options: { exitAfterInputMs?: number } = {}) {}

  async createSession(config: ProviderSessionConfig): Promise<ProviderSession> {
    const env = { ...process.env, ...config.env } as Record<string, string>;
    const apiKey = env.AMP_API_KEY?.trim();
    if (!apiKey) throw new Error("amp requires AMP_API_KEY");
    const selection = resolveAmpModel(config.model);
    const binary = resolveAmpBinary(env);
    if (!binary) {
      throw new Error(
        `amp CLI not found. Install ${AMP_PACKAGE} during image provisioning or set AMP_BINARY to a trusted executable.`,
      );
    }
    registerVolatileSecret(apiKey, "AMP_API_KEY");
    const prompt = await resolveSlashSkillPrompt(config.prompt, {
      providerLabel: "amp",
      skillsDir: join(env.HOME ?? "/home/worker", ".agents", "skills"),
    });
    // The effort rides on the plugin agent. Catalog levels exist for a pinned
    // provider/model only; a mode names no model Amp will tell us in advance.
    const effort = applyReasoningEffort("amp", selection.model, config.reasoningEffort);
    const reasoningEffort = effort.kind === "amp-effort" ? effort.reasoningEffort : null;

    const directory = await mkdtemp(join(tmpdir(), "swarm-amp-"));
    try {
      // XDG_CONFIG_HOME moves Amp's plugin directory (and settings) to this
      // per-task tree, so nothing is baked into the image or written to the repo.
      const configRoot = join(directory, "config");
      const pluginDir = join(configRoot, "amp", "plugins");
      await mkdir(pluginDir, { recursive: true });
      const settingsPath = join(configRoot, "amp", "settings.json");
      const mcpPath = join(directory, "mcp.json");
      await writeFile(
        join(pluginDir, "agent-swarm.ts"),
        buildAmpPlugin({
          baseMode: selection.baseMode,
          instructions: config.systemPrompt,
          pin: selection.pin,
          reasoningEffort: reasoningEffort ? ampEffort(reasoningEffort) : null,
        }),
        { mode: 0o600 },
      );
      await writeFile(settingsPath, JSON.stringify(buildAmpSettings()), { mode: 0o600 });
      // The bearer is in this file; the directory is removed when the session ends.
      await writeFile(mcpPath, JSON.stringify(swarmMcpConfig(config)), { mode: 0o600 });

      const childEnv: Record<string, string> = {
        ...env,
        AMP_API_KEY: apiKey,
        XDG_CONFIG_HOME: configRoot,
        AMP_SETTINGS_FILE: settingsPath,
      };
      const proc = registerProcessGroup(
        Bun.spawn(
          [
            binary,
            "-x",
            "--stream-json",
            "--stream-json-input",
            "-m",
            AMP_PLUGIN_MODE_KEY,
            // A title skips Amp's own title-generation requests (2 of 3 on a trivial turn).
            "--title",
            `swarm task ${config.taskId.slice(0, 8)}`,
            "--settings-file",
            settingsPath,
            "--mcp-config",
            mcpPath,
            "--plugin-ready-timeout",
            "30",
            // Every Amp thread is stored on ampcode.com; never share it.
            "--visibility",
            "private",
            "--no-notifications",
            "--no-ide",
            "--no-color",
          ],
          {
            cwd: config.cwd,
            env: childEnv,
            stdin: "pipe",
            stdout: "pipe",
            stderr: "pipe",
            detached: detachedProcessGroup,
          },
        ),
      );
      return new AmpSession(proc, directory, prompt, {
        selection,
        reasoningEffort,
        taskId: config.taskId,
        agentId: config.agentId,
        binary,
        cwd: config.cwd,
        env: childEnv,
        exitAfterInputMs: this.options.exitAfterInputMs ?? AMP_EXIT_AFTER_INPUT_MS,
      });
    } catch (error) {
      await rm(directory, { recursive: true, force: true });
      throw error;
    }
  }

  async canResume(_sessionId: string): Promise<boolean> {
    return false;
  }

  formatCommand(commandName: string): string {
    return `/${commandName}`;
  }
}
