// AUTO-GENERATED by scripts/generate-barrels.ts — DO NOT EDIT BY HAND.
// Phase-1 monorepo bridge: re-exports @swarm/api-client's live src/ sources so it is
// importable by package name before any files move. Regenerate after editing
// packages.map.json:  bun scripts/generate-barrels.ts

// NET-NEW package — to be GENERATED from openapi.json / the route registry in a
// later phase. Intentionally exports nothing real yet.
// TODO(phase>=2): generate a typed worker HTTP client and replace this placeholder.
export {};
