// AUTO-GENERATED by scripts/generate-barrels.ts — DO NOT EDIT BY HAND.
// Phase-1 monorepo bridge: re-exports @swarm/otel's live src/ sources so it is
// importable by package name before any files move. Regenerate after editing
// packages.map.json:  bun scripts/generate-barrels.ts

export * from "../../src/otel-impl";
export * as Otel from "../../src/otel";
export * from "../../src/telemetry";
export * from "../../src/utils/error-tracker";
