// GENERATED by scripts/gen-secret-rules.ts from scripts/vendor/gitleaks/gitleaks.toml.
// Do not edit. Run `bun run build:secret-rules` after changing the vendored config
// or the generator. 213 rules kept, 9 excluded (reasons below).

export interface GeneratedRegex {
  source: string;
  flags: string;
}

export interface GeneratedAllowlist {
  /** What the allowlist regexes test: the secret, or the whole rule match. */
  target: "secret" | "match";
  regexes: GeneratedRegex[];
  /** Lowercase; a secret containing one is allowed. */
  stopwords: string[];
}

export interface GeneratedSecretRule extends GeneratedRegex {
  id: string;
  /** Lowercase; the rule runs only when the text contains one of them. */
  keywords: string[];
  /** Minimum Shannon entropy of the secret; at or below it is not a finding. */
  entropy?: number;
  /** Capture group holding the secret. Default: the first non-empty group, else the match. */
  secretGroup?: number;
  redactWholeMatch?: boolean;
  allowlists?: GeneratedAllowlist[];
}

export interface GeneratedSecretRuleSet {
  version: string;
  commit: string;
  globalAllowlist: { regexes: GeneratedRegex[]; stopwords: string[] };
  rules: GeneratedSecretRule[];
  excluded: { id: string; reason: string }[];
}

export const GITLEAKS_RULES: GeneratedSecretRuleSet = {
  "version": "v8.30.1",
  "commit": "83d9cd684c87d95d656c1458ef04895a7f1cbd8e", // gitleaks:allow
  "globalAllowlist": {
    "regexes": [
      {
        "source": "^true|false|null$", // gitleaks:allow
        "flags": "i"
      },
      {
        "source": "^(?i:a+|b+|c+|d+|e+|f+|g+|h+|i+|j+|k+|l+|m+|n+|o+|p+|q+|r+|s+|t+|u+|v+|w+|x+|y+|z+|\\*+|\\.+)$", // gitleaks:allow
        "flags": ""
      },
      {
        "source": "^\\$(?:\\d+|{\\d+})$", // gitleaks:allow
        "flags": ""
      },
      {
        "source": "^\\$(?:[A-Z_]+|[a-z_]+)$", // gitleaks:allow
        "flags": ""
      },
      {
        "source": "^\\${(?:[A-Z_]+|[a-z_]+)}$", // gitleaks:allow
        "flags": ""
      },
      {
        "source": "^\\{\\{[ \\t]*[\\w ().|]+[ \\t]*}}$", // gitleaks:allow
        "flags": ""
      },
      {
        "source": "^\\$\\{\\{[ \\t]*(?:(?:env|github|secrets|vars)(?:\\.[A-Za-z]\\w+)+[\\w \"'&./=|]*)[ \\t]*}}$", // gitleaks:allow
        "flags": ""
      },
      {
        "source": "^%(?:[A-Z_]+|[a-z_]+)%$", // gitleaks:allow
        "flags": ""
      },
      {
        "source": "^%[+\\-# 0]?[bcdeEfFgGoOpqstTUvxX]$", // gitleaks:allow
        "flags": ""
      },
      {
        "source": "^\\{\\d{0,2}}$", // gitleaks:allow
        "flags": ""
      },
      {
        "source": "^@(?:[A-Z_]+|[a-z_]+)@$", // gitleaks:allow
        "flags": ""
      },
      {
        "source": "^/Users/(?i:[a-z0-9]+/[\\w .-/]+$)", // gitleaks:allow
        "flags": ""
      },
      {
        "source": "^/(?:bin|etc|home|opt|tmp|usr|var)/[\\w ./-]+$", // gitleaks:allow
        "flags": ""
      }
    ],
    "stopwords": [
      "014df517-39d1-4453-b7b3-9930c563627c",
      "abcdefghijklmnopqrstuvwxyz"
    ]
  },
  "rules": [
    {
      "id": "1password-secret-key",
      "source": "\\bA3-[A-Z0-9]{6}-(?:(?:[A-Z0-9]{11})|(?:[A-Z0-9]{6}-[A-Z0-9]{5}))-[A-Z0-9]{5}-[A-Z0-9]{5}-[A-Z0-9]{5}\\b", // gitleaks:allow
      "flags": "",
      "keywords": [
        "a3-"
      ],
      "entropy": 3.8
    },
    {
      "id": "1password-service-account-token",
      "source": "ops_eyJ[a-zA-Z0-9+/]{250,}={0,3}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "ops_"
      ],
      "entropy": 4
    },
    {
      "id": "adafruit-api-key",
      "source": "(?:adafruit)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9_-]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "adafruit"
      ]
    },
    {
      "id": "adobe-client-id",
      "source": "(?:adobe)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "adobe"
      ],
      "entropy": 2
    },
    {
      "id": "adobe-client-secret",
      "source": "\\b(p8e-(?i:[a-z0-9]{32}))(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "p8e-"
      ],
      "entropy": 2
    },
    {
      "id": "age-secret-key",
      "source": "AGE-SECRET-KEY-1[QPZRY9X8GF2TVDW0S3JN54KHCE6MUA7L]{58}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "age-secret-key-1"
      ]
    },
    {
      "id": "airtable-api-key",
      "source": "(?:airtable)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{17})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "airtable"
      ]
    },
    {
      "id": "airtable-personnal-access-token",
      "source": "\\b(pat[A-Za-z0-9]{14}\\.[a-f0-9]{64})\\b", // gitleaks:allow
      "flags": "",
      "keywords": [
        "airtable"
      ]
    },
    {
      "id": "algolia-api-key",
      "source": "(?:algolia)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "algolia"
      ]
    },
    {
      "id": "alibaba-access-key-id",
      "source": "\\b(LTAI(?i:[a-z0-9]{20}))(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "ltai"
      ],
      "entropy": 2
    },
    {
      "id": "alibaba-secret-key",
      "source": "(?:alibaba)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{30})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "alibaba"
      ],
      "entropy": 2
    },
    {
      "id": "anthropic-admin-api-key",
      "source": "\\b(sk-ant-admin01-[a-zA-Z0-9_\\-]{93}AA)(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "sk-ant-admin01"
      ]
    },
    {
      "id": "anthropic-api-key",
      "source": "\\b(sk-ant-api03-[a-zA-Z0-9_\\-]{93}AA)(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "sk-ant-api03"
      ]
    },
    {
      "id": "artifactory-api-key",
      "source": "\\bAKCp[A-Za-z0-9]{69}\\b", // gitleaks:allow
      "flags": "",
      "keywords": [
        "akcp"
      ],
      "entropy": 4.5
    },
    {
      "id": "artifactory-reference-token",
      "source": "\\bcmVmd[A-Za-z0-9]{59}\\b", // gitleaks:allow
      "flags": "",
      "keywords": [
        "cmvmd"
      ],
      "entropy": 4.5
    },
    {
      "id": "asana-client-id",
      "source": "(?:asana)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([0-9]{16})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "asana"
      ]
    },
    {
      "id": "asana-client-secret",
      "source": "(?:asana)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "asana"
      ]
    },
    {
      "id": "atlassian-api-token",
      "source": "(?:(?-i:ATLASSIAN|[Aa]tlassian)|(?-i:CONFLUENCE|[Cc]onfluence)|(?-i:JIRA|[Jj]ira))(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{20}[a-f0-9]{4})(?:[\\x60'\"\\s;]|\\\\[nr]|$)|\\b(ATATT3[A-Za-z0-9_\\-=]{186})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "atlassian",
        "confluence",
        "jira",
        "atatt3"
      ],
      "entropy": 3.5
    },
    {
      "id": "authress-service-client-access-key",
      "source": "\\b((?:sc|ext|scauth|authress)_(?i:[a-z0-9]{5,30}\\.[a-z0-9]{4,6}\\.(?-i:acc)[_-][a-z0-9-]{10,32}\\.[a-z0-9+/_=-]{30,120}))(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "sc_",
        "ext_",
        "scauth_",
        "authress_"
      ],
      "entropy": 2
    },
    {
      "id": "aws-access-token",
      "source": "\\b((?:A3T[A-Z0-9]|AKIA|ASIA|ABIA|ACCA)[A-Z2-7]{16})\\b", // gitleaks:allow
      "flags": "",
      "keywords": [
        "a3t",
        "akia",
        "asia",
        "abia",
        "acca"
      ],
      "entropy": 3,
      "allowlists": [
        {
          "target": "secret",
          "regexes": [
            {
              "source": ".+EXAMPLE$", // gitleaks:allow
              "flags": ""
            }
          ],
          "stopwords": []
        }
      ]
    },
    {
      "id": "aws-amazon-bedrock-api-key-long-lived",
      "source": "\\b(ABSK[A-Za-z0-9+/]{109,269}={0,2})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "absk"
      ],
      "entropy": 3
    },
    {
      "id": "aws-amazon-bedrock-api-key-short-lived",
      "source": "bedrock-api-key-YmVkcm9jay5hbWF6b25hd3MuY29t", // gitleaks:allow
      "flags": "",
      "keywords": [
        "bedrock-api-key-"
      ],
      "entropy": 3
    },
    {
      "id": "azure-ad-client-secret",
      "source": "(?:^|[\\\\'\"\\x60\\s>=:(,)])([a-zA-Z0-9_~.]{3}\\dQ~[a-zA-Z0-9_~.-]{31,34})(?:$|[\\\\'\"\\x60\\s<),])", // gitleaks:allow
      "flags": "",
      "keywords": [
        "q~"
      ],
      "entropy": 3
    },
    {
      "id": "beamer-api-token",
      "source": "(?:beamer)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(b_[a-z0-9=_\\-]{44})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "beamer"
      ]
    },
    {
      "id": "bitbucket-client-id",
      "source": "(?:bitbucket)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "bitbucket"
      ]
    },
    {
      "id": "bitbucket-client-secret",
      "source": "(?:bitbucket)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9=_\\-]{64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "bitbucket"
      ]
    },
    {
      "id": "bittrex-access-key",
      "source": "(?:bittrex)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "bittrex"
      ]
    },
    {
      "id": "bittrex-secret-key",
      "source": "(?:bittrex)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "bittrex"
      ]
    },
    {
      "id": "cisco-meraki-api-key",
      "source": "(?i:(?:(?-i:[Mm]eraki|MERAKI))(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3})(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([0-9a-f]{40})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "meraki"
      ],
      "entropy": 3
    },
    {
      "id": "clickhouse-cloud-api-secret-key",
      "source": "\\b(4b1d[A-Za-z0-9]{38})\\b", // gitleaks:allow
      "flags": "",
      "keywords": [
        "4b1d"
      ],
      "entropy": 3
    },
    {
      "id": "clojars-api-token",
      "source": "CLOJARS_[a-z0-9]{60}", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "clojars_"
      ],
      "entropy": 2
    },
    {
      "id": "cloudflare-api-key",
      "source": "(?:cloudflare)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9_-]{40})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "cloudflare"
      ],
      "entropy": 2
    },
    {
      "id": "cloudflare-global-api-key",
      "source": "(?:cloudflare)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{37})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "cloudflare"
      ],
      "entropy": 2
    },
    {
      "id": "cloudflare-origin-ca-key",
      "source": "\\b(v1\\.0-[a-f0-9]{24}-[a-f0-9]{146})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "cloudflare",
        "v1.0-"
      ],
      "entropy": 2
    },
    {
      "id": "codecov-access-token",
      "source": "(?:codecov)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "codecov"
      ]
    },
    {
      "id": "cohere-api-token",
      "source": "(?i:(?:cohere|CO_API_KEY)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3})(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-zA-Z0-9]{40})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "cohere",
        "co_api_key"
      ],
      "entropy": 4
    },
    {
      "id": "coinbase-access-token",
      "source": "(?:coinbase)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9_-]{64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "coinbase"
      ]
    },
    {
      "id": "confluent-access-token",
      "source": "(?:confluent)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{16})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "confluent"
      ]
    },
    {
      "id": "confluent-secret-key",
      "source": "(?:confluent)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "confluent"
      ]
    },
    {
      "id": "contentful-delivery-api-token",
      "source": "(?:contentful)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9=_\\-]{43})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "contentful"
      ]
    },
    {
      "id": "databricks-api-token",
      "source": "\\b(dapi[a-f0-9]{32}(?:-\\d)?)(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "dapi"
      ],
      "entropy": 3
    },
    {
      "id": "datadog-access-token",
      "source": "(?:datadog)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{40})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "datadog"
      ]
    },
    {
      "id": "defined-networking-api-token",
      "source": "(?:dnkey)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(dnkey-[a-z0-9=_\\-]{26}-[a-z0-9=_\\-]{52})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "dnkey"
      ]
    },
    {
      "id": "digitalocean-access-token",
      "source": "\\b(doo_v1_[a-f0-9]{64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "doo_v1_"
      ],
      "entropy": 3
    },
    {
      "id": "digitalocean-pat",
      "source": "\\b(dop_v1_[a-f0-9]{64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "dop_v1_"
      ],
      "entropy": 3
    },
    {
      "id": "digitalocean-refresh-token",
      "source": "\\b(dor_v1_[a-f0-9]{64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "dor_v1_"
      ]
    },
    {
      "id": "discord-api-token",
      "source": "(?:discord)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "discord"
      ]
    },
    {
      "id": "discord-client-id",
      "source": "(?:discord)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([0-9]{18})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "discord"
      ],
      "entropy": 2
    },
    {
      "id": "discord-client-secret",
      "source": "(?:discord)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9=_\\-]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "discord"
      ],
      "entropy": 2
    },
    {
      "id": "doppler-api-token",
      "source": "dp\\.pt\\.(?i:[a-z0-9]{43})", // gitleaks:allow
      "flags": "",
      "keywords": [
        "dp.pt."
      ],
      "entropy": 2
    },
    {
      "id": "droneci-access-token",
      "source": "(?:droneci)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "droneci"
      ]
    },
    {
      "id": "dropbox-api-token",
      "source": "(?:dropbox)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{15})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "dropbox"
      ]
    },
    {
      "id": "dropbox-long-lived-api-token",
      "source": "(?:dropbox)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{11}(AAAAAAAAAA)[a-z0-9\\-_=]{43})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "dropbox"
      ]
    },
    {
      "id": "dropbox-short-lived-api-token",
      "source": "(?:dropbox)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(sl\\.[a-z0-9\\-=_]{135})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "dropbox"
      ]
    },
    {
      "id": "duffel-api-token",
      "source": "duffel_(?:test|live)_(?i:[a-z0-9_\\-=]{43})", // gitleaks:allow
      "flags": "",
      "keywords": [
        "duffel_"
      ],
      "entropy": 2
    },
    {
      "id": "dynatrace-api-token",
      "source": "dt0c01\\.(?i:[a-z0-9]{24}\\.[a-z0-9]{64})", // gitleaks:allow
      "flags": "",
      "keywords": [
        "dt0c01."
      ],
      "entropy": 4
    },
    {
      "id": "easypost-api-token",
      "source": "\\bEZAK(?i:[a-z0-9]{54}\\b)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "ezak"
      ],
      "entropy": 2
    },
    {
      "id": "easypost-test-api-token",
      "source": "\\bEZTK(?i:[a-z0-9]{54}\\b)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "eztk"
      ],
      "entropy": 2
    },
    {
      "id": "etsy-access-token",
      "source": "(?:(?-i:ETSY|[Ee]tsy))(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{24})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "etsy"
      ],
      "entropy": 3
    },
    {
      "id": "facebook-access-token",
      "source": "\\b(\\d{15,16}(\\||%)[0-9a-z\\-_]{27,40})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "facebook"
      ],
      "entropy": 3
    },
    {
      "id": "facebook-page-access-token",
      "source": "\\b(EAA[MC](?i:[a-z0-9]{100,}))(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "eaam",
        "eaac"
      ],
      "entropy": 4
    },
    {
      "id": "facebook-secret",
      "source": "(?:facebook)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "facebook"
      ],
      "entropy": 3
    },
    {
      "id": "fastly-api-token",
      "source": "(?:fastly)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9=_\\-]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "fastly"
      ]
    },
    {
      "id": "finicity-api-token",
      "source": "(?:finicity)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "finicity"
      ]
    },
    {
      "id": "finicity-client-secret",
      "source": "(?:finicity)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{20})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "finicity"
      ]
    },
    {
      "id": "finnhub-access-token",
      "source": "(?:finnhub)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{20})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "finnhub"
      ]
    },
    {
      "id": "flickr-access-token",
      "source": "(?:flickr)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "flickr"
      ]
    },
    {
      "id": "flutterwave-encryption-key",
      "source": "FLWSECK_TEST-(?i:[a-h0-9]{12})", // gitleaks:allow
      "flags": "",
      "keywords": [
        "flwseck_test"
      ],
      "entropy": 2
    },
    {
      "id": "flutterwave-public-key",
      "source": "FLWPUBK_TEST-(?i:[a-h0-9]{32}-X)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "flwpubk_test"
      ],
      "entropy": 2
    },
    {
      "id": "flutterwave-secret-key",
      "source": "FLWSECK_TEST-(?i:[a-h0-9]{32}-X)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "flwseck_test"
      ],
      "entropy": 2
    },
    {
      "id": "flyio-access-token",
      "source": "\\b((?:fo1_[\\w-]{43}|fm1[ar]_[a-zA-Z0-9+\\/]{100,}={0,3}|fm2_[a-zA-Z0-9+\\/]{100,}={0,3}))(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "fo1_",
        "fm1",
        "fm2_"
      ],
      "entropy": 4
    },
    {
      "id": "frameio-api-token",
      "source": "fio-u-(?i:[a-z0-9\\-_=]{64})", // gitleaks:allow
      "flags": "",
      "keywords": [
        "fio-u-"
      ]
    },
    {
      "id": "freshbooks-access-token",
      "source": "(?:freshbooks)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "freshbooks"
      ]
    },
    {
      "id": "gcp-api-key",
      "source": "\\b(AIza[\\w-]{35})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "aiza"
      ],
      "entropy": 4
    },
    {
      "id": "github-app-token",
      "source": "(?:ghu|ghs)_[0-9a-zA-Z]{36}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "ghu_",
        "ghs_"
      ],
      "entropy": 3
    },
    {
      "id": "github-fine-grained-pat",
      "source": "github_pat_\\w{82}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "github_pat_"
      ],
      "entropy": 3
    },
    {
      "id": "github-oauth",
      "source": "gho_[0-9a-zA-Z]{36}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "gho_"
      ],
      "entropy": 3
    },
    {
      "id": "github-pat",
      "source": "ghp_[0-9a-zA-Z]{36}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "ghp_"
      ],
      "entropy": 3
    },
    {
      "id": "github-refresh-token",
      "source": "ghr_[0-9a-zA-Z]{36}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "ghr_"
      ],
      "entropy": 3
    },
    {
      "id": "gitlab-cicd-job-token",
      "source": "glcbt-[0-9a-zA-Z]{1,5}_[0-9a-zA-Z_-]{20}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "glcbt-"
      ],
      "entropy": 3
    },
    {
      "id": "gitlab-deploy-token",
      "source": "gldt-[0-9a-zA-Z_\\-]{20}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "gldt-"
      ],
      "entropy": 3
    },
    {
      "id": "gitlab-feature-flag-client-token",
      "source": "glffct-[0-9a-zA-Z_\\-]{20}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "glffct-"
      ],
      "entropy": 3
    },
    {
      "id": "gitlab-feed-token",
      "source": "glft-[0-9a-zA-Z_\\-]{20}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "glft-"
      ],
      "entropy": 3
    },
    {
      "id": "gitlab-incoming-mail-token",
      "source": "glimt-[0-9a-zA-Z_\\-]{25}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "glimt-"
      ],
      "entropy": 3
    },
    {
      "id": "gitlab-kubernetes-agent-token",
      "source": "glagent-[0-9a-zA-Z_\\-]{50}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "glagent-"
      ],
      "entropy": 3
    },
    {
      "id": "gitlab-oauth-app-secret",
      "source": "gloas-[0-9a-zA-Z_\\-]{64}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "gloas-"
      ],
      "entropy": 3
    },
    {
      "id": "gitlab-pat",
      "source": "glpat-[\\w-]{20}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "glpat-"
      ],
      "entropy": 3
    },
    {
      "id": "gitlab-pat-routable",
      "source": "\\bglpat-[0-9a-zA-Z_-]{27,300}\\.[0-9a-z]{2}[0-9a-z]{7}\\b", // gitleaks:allow
      "flags": "",
      "keywords": [
        "glpat-"
      ],
      "entropy": 4
    },
    {
      "id": "gitlab-ptt",
      "source": "glptt-[0-9a-f]{40}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "glptt-"
      ],
      "entropy": 3
    },
    {
      "id": "gitlab-rrt",
      "source": "GR1348941[\\w-]{20}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "gr1348941"
      ],
      "entropy": 3
    },
    {
      "id": "gitlab-runner-authentication-token",
      "source": "glrt-[0-9a-zA-Z_\\-]{20}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "glrt-"
      ],
      "entropy": 3
    },
    {
      "id": "gitlab-runner-authentication-token-routable",
      "source": "\\bglrt-t\\d_[0-9a-zA-Z_\\-]{27,300}\\.[0-9a-z]{2}[0-9a-z]{7}\\b", // gitleaks:allow
      "flags": "",
      "keywords": [
        "glrt-"
      ],
      "entropy": 4
    },
    {
      "id": "gitlab-scim-token",
      "source": "glsoat-[0-9a-zA-Z_\\-]{20}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "glsoat-"
      ],
      "entropy": 3
    },
    {
      "id": "gitlab-session-cookie",
      "source": "_gitlab_session=[0-9a-z]{32}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "_gitlab_session="
      ],
      "entropy": 3
    },
    {
      "id": "gitter-access-token",
      "source": "(?:gitter)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9_-]{40})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "gitter"
      ]
    },
    {
      "id": "gocardless-api-token",
      "source": "(?:gocardless)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(live_[a-z0-9\\-_=]{40})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "live_",
        "gocardless"
      ]
    },
    {
      "id": "grafana-api-key",
      "source": "\\b(eyJrIjoi[A-Za-z0-9]{70,400}={0,3})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "eyjrijoi"
      ],
      "entropy": 3
    },
    {
      "id": "grafana-cloud-api-token",
      "source": "\\b(glc_[A-Za-z0-9+/]{32,400}={0,3})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "glc_"
      ],
      "entropy": 3
    },
    {
      "id": "grafana-service-account-token",
      "source": "\\b(glsa_[A-Za-z0-9]{32}_[A-Fa-f0-9]{8})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "glsa_"
      ],
      "entropy": 3
    },
    {
      "id": "harness-api-key",
      "source": "(?:pat|sat)\\.[a-zA-Z0-9_-]{22}\\.[a-zA-Z0-9]{24}\\.[a-zA-Z0-9]{20}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "pat.",
        "sat."
      ]
    },
    {
      "id": "hashicorp-tf-api-token",
      "source": "[a-z0-9]{14}\\.(?-i:atlasv1)\\.[a-z0-9\\-_=]{60,70}", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "atlasv1"
      ],
      "entropy": 3.5
    },
    {
      "id": "heroku-api-key",
      "source": "(?:heroku)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "heroku"
      ]
    },
    {
      "id": "heroku-api-key-v2",
      "source": "\\b((HRKU-AA[0-9a-zA-Z_-]{58}))(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "hrku-aa"
      ],
      "entropy": 4
    },
    {
      "id": "hubspot-api-key",
      "source": "(?:hubspot)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "hubspot"
      ]
    },
    {
      "id": "huggingface-access-token",
      "source": "\\b(hf_(?i:[a-z]{34}))(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "hf_"
      ],
      "entropy": 2
    },
    {
      "id": "huggingface-organization-api-token",
      "source": "\\b(api_org_(?i:[a-z]{34}))(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "api_org_"
      ],
      "entropy": 2
    },
    {
      "id": "infracost-api-token",
      "source": "\\b(ico-[a-zA-Z0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "ico-"
      ],
      "entropy": 3
    },
    {
      "id": "intercom-api-key",
      "source": "(?:intercom)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9=_\\-]{60})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "intercom"
      ]
    },
    {
      "id": "intra42-client-secret",
      "source": "\\b(s-s4t2(?:ud|af)-(?i:[abcdef0123456789]{64}))(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "intra",
        "s-s4t2ud-",
        "s-s4t2af-"
      ],
      "entropy": 3
    },
    {
      "id": "jfrog-api-key",
      "source": "(?:jfrog|artifactory|bintray|xray)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{73})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "jfrog",
        "artifactory",
        "bintray",
        "xray"
      ]
    },
    {
      "id": "jfrog-identity-token",
      "source": "(?:jfrog|artifactory|bintray|xray)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "jfrog",
        "artifactory",
        "bintray",
        "xray"
      ]
    },
    {
      "id": "jwt",
      "source": "\\b(ey[a-zA-Z0-9]{17,}\\.ey[a-zA-Z0-9\\/\\\\_-]{17,}\\.(?:[a-zA-Z0-9\\/\\\\_-]{10,}={0,2})?)(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "ey"
      ],
      "entropy": 3
    },
    {
      "id": "jwt-base64",
      "source": "\\bZXlK(?:(?<alg>aGJHY2lPaU)|(?<apu>aGNIVWlPaU)|(?<apv>aGNIWWlPaU)|(?<aud>aGRXUWlPaU)|(?<b64>aU5qUWlP)|(?<crit>amNtbDBJanBi)|(?<cty>amRIa2lPaU)|(?<epk>bGNHc2lPbn)|(?<enc>bGJtTWlPaU)|(?<jku>cWEzVWlPaU)|(?<jwk>cWQyc2lPb)|(?<iss>cGMzTWlPaU)|(?<iv>cGRpSTZJ)|(?<kid>cmFXUWlP)|(?<key_ops>clpYbGZiM0J6SWpwY)|(?<kty>cmRIa2lPaUp)|(?<nonce>dWIyNWpaU0k2)|(?<p2c>d01tTWlP)|(?<p2s>d01uTWlPaU)|(?<ppt>d2NIUWlPaU)|(?<sub>emRXSWlPaU)|(?<svt>emRuUWlP)|(?<tag>MFlXY2lPaU)|(?<typ>MGVYQWlPaUp)|(?<url>MWNtd2l)|(?<use>MWMyVWlPaUp)|(?<ver>MlpYSWlPaU)|(?<version>MlpYSnphVzl1SWpv)|(?<x>NElqb2)|(?<x5c>NE5XTWlP)|(?<x5t>NE5YUWlPaU)|(?<x5ts256>NE5YUWpVekkxTmlJNkl)|(?<x5u>NE5YVWlPaU)|(?<zip>NmFYQWlPaU))[a-zA-Z0-9\\/\\\\_+\\-\\r\\n]{40,}={0,2}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "zxlk"
      ],
      "entropy": 2,
      "redactWholeMatch": true
    },
    {
      "id": "kraken-access-token",
      "source": "(?:kraken)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9\\/=_\\+\\-]{80,90})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "kraken"
      ]
    },
    {
      "id": "kucoin-access-token",
      "source": "(?:kucoin)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{24})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "kucoin"
      ]
    },
    {
      "id": "kucoin-secret-key",
      "source": "(?:kucoin)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "kucoin"
      ]
    },
    {
      "id": "launchdarkly-access-token",
      "source": "(?:launchdarkly)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9=_\\-]{40})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "launchdarkly"
      ]
    },
    {
      "id": "linear-api-key",
      "source": "lin_api_(?i:[a-z0-9]{40})", // gitleaks:allow
      "flags": "",
      "keywords": [
        "lin_api_"
      ],
      "entropy": 2
    },
    {
      "id": "linear-client-secret",
      "source": "(?:linear)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "linear"
      ],
      "entropy": 2
    },
    {
      "id": "linkedin-client-id",
      "source": "(?:linked[_-]?in)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{14})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "linkedin",
        "linked_in",
        "linked-in"
      ],
      "entropy": 2
    },
    {
      "id": "linkedin-client-secret",
      "source": "(?:linked[_-]?in)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{16})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "linkedin",
        "linked_in",
        "linked-in"
      ],
      "entropy": 2
    },
    {
      "id": "lob-api-key",
      "source": "(?:lob)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}((live|test)_[a-f0-9]{35})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "test_",
        "live_"
      ]
    },
    {
      "id": "lob-pub-api-key",
      "source": "(?:lob)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}((test|live)_pub_[a-f0-9]{31})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "test_pub",
        "live_pub",
        "_pub"
      ]
    },
    {
      "id": "looker-client-id",
      "source": "(?:looker)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{20})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "looker"
      ]
    },
    {
      "id": "looker-client-secret",
      "source": "(?:looker)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{24})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "looker"
      ]
    },
    {
      "id": "mailchimp-api-key",
      "source": "(?:MailchimpSDK.initialize|mailchimp)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{32}-us\\d\\d)(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "mailchimp"
      ]
    },
    {
      "id": "mailgun-private-api-token",
      "source": "(?:mailgun)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(key-[a-f0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "mailgun"
      ]
    },
    {
      "id": "mailgun-pub-key",
      "source": "(?:mailgun)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(pubkey-[a-f0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "mailgun"
      ]
    },
    {
      "id": "mailgun-signing-key",
      "source": "(?:mailgun)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-h0-9]{32}-[a-h0-9]{8}-[a-h0-9]{8})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "mailgun"
      ]
    },
    {
      "id": "mapbox-api-token",
      "source": "(?:mapbox)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(pk\\.[a-z0-9]{60}\\.[a-z0-9]{22})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "mapbox"
      ]
    },
    {
      "id": "mattermost-access-token",
      "source": "(?:mattermost)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{26})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "mattermost"
      ]
    },
    {
      "id": "maxmind-license-key",
      "source": "\\b([A-Za-z0-9]{6}_[A-Za-z0-9]{29}_mmk)(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "_mmk"
      ],
      "entropy": 4
    },
    {
      "id": "messagebird-api-token",
      "source": "(?:message[_-]?bird)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{25})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "messagebird",
        "message-bird",
        "message_bird"
      ]
    },
    {
      "id": "messagebird-client-id",
      "source": "(?:message[_-]?bird)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "messagebird",
        "message-bird",
        "message_bird"
      ]
    },
    {
      "id": "microsoft-teams-webhook",
      "source": "https://[a-z0-9]+\\.webhook\\.office\\.com/webhookb2/[a-z0-9]{8}-([a-z0-9]{4}-){3}[a-z0-9]{12}@[a-z0-9]{8}-([a-z0-9]{4}-){3}[a-z0-9]{12}/IncomingWebhook/[a-z0-9]{32}/[a-z0-9]{8}-([a-z0-9]{4}-){3}[a-z0-9]{12}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "webhook.office.com",
        "webhookb2",
        "incomingwebhook"
      ]
    },
    {
      "id": "netlify-access-token",
      "source": "(?:netlify)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9=_\\-]{40,46})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "netlify"
      ]
    },
    {
      "id": "new-relic-browser-api-token",
      "source": "(?:new-relic|newrelic|new_relic)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(NRJS-[a-f0-9]{19})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "nrjs-"
      ]
    },
    {
      "id": "new-relic-insert-key",
      "source": "(?:new-relic|newrelic|new_relic)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(NRII-[a-z0-9-]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "nrii-"
      ]
    },
    {
      "id": "new-relic-user-api-id",
      "source": "(?:new-relic|newrelic|new_relic)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "new-relic",
        "newrelic",
        "new_relic"
      ]
    },
    {
      "id": "new-relic-user-api-key",
      "source": "(?:new-relic|newrelic|new_relic)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(NRAK-[a-z0-9]{27})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "nrak"
      ]
    },
    {
      "id": "notion-api-token",
      "source": "\\b(ntn_[0-9]{11}[A-Za-z0-9]{32}[A-Za-z0-9]{3})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "ntn_"
      ],
      "entropy": 4
    },
    {
      "id": "npm-access-token",
      "source": "\\b(npm_[a-z0-9]{36})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "npm_"
      ],
      "entropy": 2
    },
    {
      "id": "nytimes-access-token",
      "source": "(?:nytimes|new-york-times,|newyorktimes)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9=_\\-]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "nytimes",
        "new-york-times",
        "newyorktimes"
      ]
    },
    {
      "id": "octopus-deploy-api-key",
      "source": "\\b(API-[A-Z0-9]{26})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "api-"
      ],
      "entropy": 3
    },
    {
      "id": "okta-access-token",
      "source": "(?i:(?:(?-i:[Oo]kta|OKTA))(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3})(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(00[\\w=\\-]{40})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "okta"
      ],
      "entropy": 4
    },
    {
      "id": "openai-api-key",
      "source": "\\b(sk-(?:proj|svcacct|admin)-(?:[A-Za-z0-9_-]{74}|[A-Za-z0-9_-]{58})T3BlbkFJ(?:[A-Za-z0-9_-]{74}|[A-Za-z0-9_-]{58})\\b|sk-[a-zA-Z0-9]{20}T3BlbkFJ[a-zA-Z0-9]{20})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "t3blbkfj"
      ],
      "entropy": 3
    },
    {
      "id": "openshift-user-token",
      "source": "\\b(sha256~[\\w-]{43})(?:[^\\w-]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "sha256~"
      ],
      "entropy": 3.5
    },
    {
      "id": "perplexity-api-key",
      "source": "\\b(pplx-[a-zA-Z0-9]{48})(?:[\\x60'\"\\s;]|\\\\[nr]|$|\\b)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "pplx-"
      ],
      "entropy": 4
    },
    {
      "id": "plaid-api-token",
      "source": "(?:plaid)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(access-(?:sandbox|development|production)-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "plaid"
      ]
    },
    {
      "id": "plaid-client-id",
      "source": "(?:plaid)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{24})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "plaid"
      ],
      "entropy": 3.5
    },
    {
      "id": "plaid-secret-key",
      "source": "(?:plaid)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{30})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "plaid"
      ],
      "entropy": 3.5
    },
    {
      "id": "planetscale-api-token",
      "source": "\\b(pscale_tkn_(?i:[\\w=\\.-]{32,64}))(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "pscale_tkn_"
      ],
      "entropy": 3
    },
    {
      "id": "planetscale-oauth-token",
      "source": "\\b(pscale_oauth_[\\w=\\.-]{32,64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "pscale_oauth_"
      ],
      "entropy": 3
    },
    {
      "id": "planetscale-password",
      "source": "\\b(pscale_pw_[\\w=\\.-]{32,64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "pscale_pw_"
      ],
      "entropy": 3
    },
    {
      "id": "postman-api-token",
      "source": "\\b(PMAK-(?i:[a-f0-9]{24}\\-[a-f0-9]{34}))(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "pmak-"
      ],
      "entropy": 3
    },
    {
      "id": "prefect-api-token",
      "source": "\\b(pnu_[a-zA-Z0-9]{36})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "pnu_"
      ],
      "entropy": 2
    },
    {
      "id": "privateai-api-token",
      "source": "(?i:(?:private[_-]?ai)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3})(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "privateai",
        "private_ai",
        "private-ai"
      ],
      "entropy": 3
    },
    {
      "id": "pulumi-api-token",
      "source": "\\b(pul-[a-f0-9]{40})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "pul-"
      ],
      "entropy": 2
    },
    {
      "id": "pypi-upload-token",
      "source": "pypi-AgEIcHlwaS5vcmc[\\w-]{50,1000}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "pypi-ageichlwas5vcmc"
      ],
      "entropy": 3
    },
    {
      "id": "rapidapi-access-token",
      "source": "(?:rapidapi)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9_-]{50})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "rapidapi"
      ]
    },
    {
      "id": "readme-api-token",
      "source": "\\b(rdme_[a-z0-9]{70})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "rdme_"
      ],
      "entropy": 2
    },
    {
      "id": "rubygems-api-token",
      "source": "\\b(rubygems_[a-f0-9]{48})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "rubygems_"
      ],
      "entropy": 2
    },
    {
      "id": "scalingo-api-token",
      "source": "\\b(tk-us-[\\w-]{48})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "tk-us-"
      ],
      "entropy": 2
    },
    {
      "id": "sendbird-access-id",
      "source": "(?:sendbird)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "sendbird"
      ]
    },
    {
      "id": "sendbird-access-token",
      "source": "(?:sendbird)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{40})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "sendbird"
      ]
    },
    {
      "id": "sendgrid-api-token",
      "source": "\\b(SG\\.(?i:[a-z0-9=_\\-\\.]{66}))(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "sg."
      ],
      "entropy": 2
    },
    {
      "id": "sendinblue-api-token",
      "source": "\\b(xkeysib-[a-f0-9]{64}\\-(?i:[a-z0-9]{16}))(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "xkeysib-"
      ],
      "entropy": 2
    },
    {
      "id": "sentry-access-token",
      "source": "(?:sentry)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "sentry"
      ],
      "entropy": 3
    },
    {
      "id": "sentry-org-token",
      "source": "\\bsntrys_eyJpYXQiO[a-zA-Z0-9+/]{10,200}(?:LCJyZWdpb25fdXJs|InJlZ2lvbl91cmwi|cmVnaW9uX3VybCI6)[a-zA-Z0-9+/]{10,200}={0,2}_[a-zA-Z0-9+/]{43}(?:[^a-zA-Z0-9+/]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "sntrys_eyjpyxqio"
      ],
      "entropy": 4.5
    },
    {
      "id": "sentry-user-token",
      "source": "\\b(sntryu_[a-f0-9]{64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "sntryu_"
      ],
      "entropy": 3.5
    },
    {
      "id": "settlemint-application-access-token",
      "source": "\\b(sm_aat_[a-zA-Z0-9]{16})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "sm_aat"
      ],
      "entropy": 3
    },
    {
      "id": "settlemint-personal-access-token",
      "source": "\\b(sm_pat_[a-zA-Z0-9]{16})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "sm_pat"
      ],
      "entropy": 3
    },
    {
      "id": "settlemint-service-access-token",
      "source": "\\b(sm_sat_[a-zA-Z0-9]{16})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "sm_sat"
      ],
      "entropy": 3
    },
    {
      "id": "shippo-api-token",
      "source": "\\b(shippo_(?:live|test)_[a-fA-F0-9]{40})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "shippo_"
      ],
      "entropy": 2
    },
    {
      "id": "shopify-access-token",
      "source": "shpat_[a-fA-F0-9]{32}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "shpat_"
      ],
      "entropy": 2
    },
    {
      "id": "shopify-custom-access-token",
      "source": "shpca_[a-fA-F0-9]{32}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "shpca_"
      ],
      "entropy": 2
    },
    {
      "id": "shopify-private-app-access-token",
      "source": "shppa_[a-fA-F0-9]{32}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "shppa_"
      ],
      "entropy": 2
    },
    {
      "id": "shopify-shared-secret",
      "source": "shpss_[a-fA-F0-9]{32}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "shpss_"
      ],
      "entropy": 2
    },
    {
      "id": "sidekiq-secret",
      "source": "(?:BUNDLE_ENTERPRISE__CONTRIBSYS__COM|BUNDLE_GEMS__CONTRIBSYS__COM)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-f0-9]{8}:[a-f0-9]{8})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "bundle_enterprise__contribsys__com",
        "bundle_gems__contribsys__com"
      ]
    },
    {
      "id": "sidekiq-sensitive-url",
      "source": "\\bhttps?://([a-f0-9]{8}:[a-f0-9]{8})@(?:gems.contribsys.com|enterprise.contribsys.com)(?:[\\/|\\#|\\?|:]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "gems.contribsys.com",
        "enterprise.contribsys.com"
      ]
    },
    {
      "id": "slack-app-token",
      "source": "xapp-\\d-[A-Z0-9]+-\\d+-[a-z0-9]+", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "xapp"
      ],
      "entropy": 2
    },
    {
      "id": "slack-bot-token",
      "source": "xoxb-[0-9]{10,13}-[0-9]{10,13}[a-zA-Z0-9-]*", // gitleaks:allow
      "flags": "",
      "keywords": [
        "xoxb"
      ],
      "entropy": 3
    },
    {
      "id": "slack-config-access-token",
      "source": "xoxe.xox[bp]-\\d-[A-Z0-9]{163,166}", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "xoxe.xoxb-",
        "xoxe.xoxp-"
      ],
      "entropy": 2
    },
    {
      "id": "slack-config-refresh-token",
      "source": "xoxe-\\d-[A-Z0-9]{146}", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "xoxe-"
      ],
      "entropy": 2
    },
    {
      "id": "slack-legacy-bot-token",
      "source": "xoxb-[0-9]{8,14}-[a-zA-Z0-9]{18,26}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "xoxb"
      ],
      "entropy": 2
    },
    {
      "id": "slack-legacy-token",
      "source": "xox[os]-\\d+-\\d+-\\d+-[a-fA-F\\d]+", // gitleaks:allow
      "flags": "",
      "keywords": [
        "xoxo",
        "xoxs"
      ],
      "entropy": 2
    },
    {
      "id": "slack-legacy-workspace-token",
      "source": "xox[ar]-(?:\\d-)?[0-9a-zA-Z]{8,48}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "xoxa",
        "xoxr"
      ],
      "entropy": 2
    },
    {
      "id": "slack-user-token",
      "source": "xox[pe](?:-[0-9]{10,13}){3}-[a-zA-Z0-9-]{28,34}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "xoxp-",
        "xoxe-"
      ],
      "entropy": 2
    },
    {
      "id": "slack-webhook-url",
      "source": "(?:https?://)?hooks.slack.com/(?:services|workflows|triggers)/[A-Za-z0-9+/]{43,56}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "hooks.slack.com"
      ]
    },
    {
      "id": "snyk-api-token",
      "source": "(?:snyk[_.-]?(?:(?:api|oauth)[_.-]?)?(?:key|token))(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "snyk"
      ]
    },
    {
      "id": "sonar-api-token",
      "source": "(?:sonar[_.-]?(login|token))(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}((?:squ_|sqp_|sqa_)?[a-z0-9=_\\-]{40})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "sonar"
      ],
      "secretGroup": 2
    },
    {
      "id": "sourcegraph-access-token",
      "source": "\\b(\\b(sgp_(?:[a-fA-F0-9]{16}|local)_[a-fA-F0-9]{40}|sgp_[a-fA-F0-9]{40})\\b)(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "sgp_",
        "sourcegraph"
      ],
      "entropy": 3
    },
    {
      "id": "square-access-token",
      "source": "\\b((?:EAAA|sq0atp-)[\\w-]{22,60})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "sq0atp-",
        "eaaa"
      ],
      "entropy": 2
    },
    {
      "id": "squarespace-access-token",
      "source": "(?:squarespace)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "squarespace"
      ]
    },
    {
      "id": "stripe-access-token",
      "source": "\\b((?:sk|rk)_(?:test|live|prod)_[a-zA-Z0-9]{10,99})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "sk_test",
        "sk_live",
        "sk_prod",
        "rk_test",
        "rk_live",
        "rk_prod"
      ],
      "entropy": 2
    },
    {
      "id": "sumologic-access-id",
      "source": "(?i:(?:(?-i:[Ss]umo|SUMO))(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3})(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(su[a-zA-Z0-9]{12})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "sumo"
      ],
      "entropy": 3
    },
    {
      "id": "sumologic-access-token",
      "source": "(?:(?-i:[Ss]umo|SUMO))(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{64})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "sumo"
      ],
      "entropy": 3
    },
    {
      "id": "telegram-bot-api-token",
      "source": "(?:telegr)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([0-9]{5,16}:(?-i:A)[a-z0-9_\\-]{34})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "telegr"
      ]
    },
    {
      "id": "travisci-access-token",
      "source": "(?:travis)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{22})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "travis"
      ]
    },
    {
      "id": "twilio-api-key",
      "source": "SK[0-9a-fA-F]{32}", // gitleaks:allow
      "flags": "",
      "keywords": [
        "sk"
      ],
      "entropy": 3
    },
    {
      "id": "twitch-api-token",
      "source": "(?:twitch)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{30})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "twitch"
      ]
    },
    {
      "id": "twitter-access-secret",
      "source": "(?:twitter)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{45})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "twitter"
      ]
    },
    {
      "id": "twitter-access-token",
      "source": "(?:twitter)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([0-9]{15,25}-[a-zA-Z0-9]{20,40})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "twitter"
      ]
    },
    {
      "id": "twitter-api-key",
      "source": "(?:twitter)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{25})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "twitter"
      ]
    },
    {
      "id": "twitter-api-secret",
      "source": "(?:twitter)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{50})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "twitter"
      ]
    },
    {
      "id": "twitter-bearer-token",
      "source": "(?:twitter)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(A{22}[a-zA-Z0-9%]{80,100})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "twitter"
      ]
    },
    {
      "id": "typeform-api-token",
      "source": "(?:typeform)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(tfp_[a-z0-9\\-_\\.=]{59})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "tfp_"
      ]
    },
    {
      "id": "vault-batch-token",
      "source": "\\b(hvb\\.[\\w-]{138,300})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "hvb."
      ],
      "entropy": 4
    },
    {
      "id": "vault-service-token",
      "source": "\\b((?:hvs\\.[\\w-]{90,120}|s\\.(?i:[a-z0-9]{24})))(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "",
      "keywords": [
        "hvs.",
        "s."
      ],
      "entropy": 3.5,
      "allowlists": [
        {
          "target": "secret",
          "regexes": [
            {
              "source": "^(?:s\\.[A-Za-z]{24})$", // gitleaks:allow
              "flags": ""
            }
          ],
          "stopwords": []
        }
      ]
    },
    {
      "id": "yandex-access-token",
      "source": "(?:yandex)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(t1\\.[A-Z0-9a-z_-]+[=]{0,2}\\.[A-Z0-9a-z_-]{86}[=]{0,2})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "yandex"
      ]
    },
    {
      "id": "yandex-api-key",
      "source": "(?:yandex)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(AQVN[A-Za-z0-9_\\-]{35,38})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "yandex"
      ]
    },
    {
      "id": "yandex-aws-access-token",
      "source": "(?:yandex)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}(YC[a-zA-Z0-9_\\-]{38})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "yandex"
      ]
    },
    {
      "id": "zendesk-secret-key",
      "source": "(?:zendesk)(?:[ \\t\\w.-]{0,20})[\\s'\"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60'\"\\s=]{0,5}([a-z0-9]{40})(?:[\\x60'\"\\s;]|\\\\[nr]|$)", // gitleaks:allow
      "flags": "i",
      "keywords": [
        "zendesk"
      ]
    }
  ],
  "excluded": [
    {
      "id": "curl-auth-header",
      "reason": "the key-context pass already redacts auth headers; its unbounded multi-line `.*?` backtracks in JS"
    },
    {
      "id": "curl-auth-user",
      "reason": "the key-context pass already redacts curl -u/--user; its unbounded multi-line `.*` backtracks in JS"
    },
    {
      "id": "freemius-secret-key",
      "reason": "path-scoped: gitleaks applies it to matching file names only"
    },
    {
      "id": "generic-api-key",
      "reason": "entropy on any key-like word; noisy on agent prose, and the scrubber's key-context pass covers sensitive keys"
    },
    {
      "id": "hashicorp-tf-password",
      "reason": "path-scoped: gitleaks applies it to matching file names only"
    },
    {
      "id": "kubernetes-secret-yaml",
      "reason": "path-scoped: gitleaks applies it to matching file names only"
    },
    {
      "id": "nuget-config-password",
      "reason": "path-scoped: gitleaks applies it to matching file names only"
    },
    {
      "id": "pkcs12-file",
      "reason": "path-scoped: gitleaks applies it to matching file names only"
    },
    {
      "id": "private-key",
      "reason": "the key-context pass already redacts PEM private-key blocks"
    }
  ]
};
