// AUTO-GENERATED by scripts/generate-barrels.ts — DO NOT EDIT BY HAND.
// Phase-1 monorepo bridge: re-exports @swarm/prompt-templates's live src/ sources so it is
// importable by package name before any files move. Regenerate after editing
// packages.map.json:  bun scripts/generate-barrels.ts

export * from "../../src/heartbeat/templates";
export * from "../../src/prompts/base-prompt";
export * from "../../src/prompts/defaults";
export * from "../../src/prompts/memories";
export * from "../../src/prompts/registry";
export * from "../../src/prompts/resolver";
export * from "../../src/prompts/session-templates";
