#!/usr/bin/env bun
/**
 * build-claude-mod: bundle the dashboard's session-log parser
 * (apps/ui/src/logs-parser) into claude-mod/vendor/logs-parser.js, so the
 * Claude Code mod renders task logs with the same code as the dashboard.
 * A mod loads only files inside its plugin, so it cannot import apps/ui.
 *
 *   bun scripts/build-claude-mod.ts          # rewrite the bundle
 *   bun scripts/build-claude-mod.ts --check  # exit 1 when the bundle is stale
 */

const ENTRY = "apps/ui/src/logs-parser/index.ts";
const OUT = "claude-mod/vendor/logs-parser.js";
const HEADER = `// Generated by scripts/build-claude-mod.ts from ${ENTRY}. Do not edit.\n// Rebuild: bun run build:claude-mod\n`;

const result = await Bun.build({
  entrypoints: [ENTRY],
  format: "esm",
  target: "browser",
  minify: false,
});
if (!result.success || !result.outputs[0]) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}
const code = HEADER + (await result.outputs[0].text());

if (process.argv.includes("--check")) {
  const file = Bun.file(OUT);
  const current = (await file.exists()) ? await file.text() : "";
  if (current !== code) {
    console.error(`${OUT} is stale. Run: bun run build:claude-mod`);
    process.exit(1);
  }
  console.log(`${OUT} is up to date.`);
} else {
  await Bun.write(OUT, code);
  console.log(`Wrote ${OUT}`);
}
