#!/usr/bin/env bun
/**
 * build-claude-mod: bundle the dashboard's session-log parser
 * (apps/ui/src/logs-parser) into claude-mod/vendor/logs-parser.js, so the
 * Claude Code mod renders task logs with the same code as the dashboard.
 * A mod loads only files inside its plugin, so it cannot import apps/ui.
 *
 * The bundle's header carries a hash of the parser's source files. `--check`
 * compares that hash, not the bundle bytes: bundler output differs between
 * Bun versions, the source does not.
 *
 *   bun scripts/build-claude-mod.ts          # rewrite the bundle
 *   bun scripts/build-claude-mod.ts --check  # exit 1 when the source changed since the last build
 */

const ENTRY = "apps/ui/src/logs-parser/index.ts";
const SOURCES = ["apps/ui/src/logs-parser/**/*.ts", "src/utils/dsh-usage.ts"];
const OUT = "claude-mod/vendor/logs-parser.js";

async function sourceHash(): Promise<string> {
  const files = new Set<string>();
  for (const pattern of SOURCES) {
    for await (const file of new Bun.Glob(pattern).scan(".")) files.add(file);
  }
  const hasher = new Bun.CryptoHasher("sha256");
  for (const file of [...files].sort()) {
    hasher.update(`${file}\n`);
    hasher.update(await Bun.file(file).text());
  }
  return hasher.digest("hex").slice(0, 16);
}

const hash = await sourceHash();
const stamp = `// Source hash: ${hash}`;

if (process.argv.includes("--check")) {
  const file = Bun.file(OUT);
  const current = (await file.exists()) ? await file.text() : "";
  if (!current.split("\n", 4).includes(stamp)) {
    console.error(`${OUT} is stale: the parser source changed. Run: bun run build:claude-mod`);
    process.exit(1);
  }
  console.log(`${OUT} is up to date.`);
  process.exit(0);
}

const result = await Bun.build({
  entrypoints: [ENTRY],
  format: "esm",
  target: "browser",
  minify: false,
});
if (!result.success || !result.outputs[0]) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}
const header = [
  `// Generated by scripts/build-claude-mod.ts from ${ENTRY}. Do not edit.`,
  "// Rebuild: bun run build:claude-mod",
  stamp,
].join("\n");
await Bun.write(OUT, `${header}\n${await result.outputs[0].text()}`);
console.log(`Wrote ${OUT}`);
