#!/usr/bin/env bun
import { resolve } from "node:path";
import ts from "typescript";

const CONTRACT_FILE = resolve("src/extensions/contract.ts");
const OUTPUT_FILE = "src/scripts-runtime/types/swarm-extension.d.ts";
const CONSTANT_FILE = "src/extensions/contract-types.generated.ts";

function renderExportedType(program: ts.Program, fileName: string, exportName: string): string {
  const checker = program.getTypeChecker();
  const sourceFile = program.getSourceFile(resolve(fileName));
  if (!sourceFile) throw new Error(`Source file not found: ${fileName}`);
  const moduleSymbol = checker.getSymbolAtLocation(sourceFile);
  const symbol = moduleSymbol
    ? checker.getExportsOfModule(moduleSymbol).find((candidate) => candidate.name === exportName)
    : undefined;
  if (!symbol) throw new Error(`Export not found: ${fileName}#${exportName}`);
  const type = checker.getDeclaredTypeOfSymbol(symbol);
  return checker.typeToString(
    type,
    undefined,
    ts.TypeFormatFlags.NoTruncation |
      ts.TypeFormatFlags.InTypeAlias |
      ts.TypeFormatFlags.MultilineObjectLiterals |
      ts.TypeFormatFlags.UseStructuralFallback,
  );
}

async function main() {
  let declaration = "";
  const options: ts.CompilerOptions = {
    allowImportingTsExtensions: true,
    baseUrl: resolve("."),
    declaration: true,
    emitDeclarationOnly: true,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    paths: { "@/*": ["src/*"] },
    skipLibCheck: true,
    strict: true,
    target: ts.ScriptTarget.ES2022,
    types: ["bun"],
  };
  const program = ts.createProgram(
    [CONTRACT_FILE, resolve("src/scripts-runtime/types/swarm-sdk.d.ts")],
    options,
  );
  const emit = program.emit(undefined, (fileName, data) => {
    if (fileName.endsWith("contract.d.ts")) declaration = data;
  });
  const diagnostics = [...ts.getPreEmitDiagnostics(program), ...emit.diagnostics];
  if (diagnostics.length > 0) {
    throw new Error(
      ts.formatDiagnosticsWithColorAndContext(diagnostics, {
        getCanonicalFileName: (fileName) => fileName,
        getCurrentDirectory: () => process.cwd(),
        getNewLine: () => "\n",
      }),
    );
  }
  if (!declaration) throw new Error("TypeScript did not emit the extension contract declaration");

  const inlinedTypes = [
    ["CreateTaskOptions", "src/types.ts"],
    ["AgentTask", "src/types.ts"],
    ["ActiveSession", "src/types.ts"],
    ["RequestInfo", "src/tools/utils.ts"],
  ]
    .map(
      ([name, fileName]) =>
        `export type ${name} = ${renderExportedType(program, fileName!, name!)};`,
    )
    .join("\n\n");
  const portableDeclaration = declaration
    .replace(/^import type .* from "\.\.[^"]+";\n/gm, "")
    .replace(/^export \{\};?\n?/gm, "")
    .replace(/\n{3,}/g, "\n\n");
  const moduleBody = `${inlinedTypes}\n\n${portableDeclaration}`.trim();

  await Bun.$`mkdir -p src/scripts-runtime/types`;
  await Bun.write(
    OUTPUT_FILE,
    `// biome-ignore-all lint/suspicious/noConfusingVoidType: Extension handlers may explicitly return no result.\ndeclare module "swarm-extension" {\n${moduleBody.replace(/^/gm, "  ")}\n}\n`,
  );
  await Bun.$`bunx biome format --write ${OUTPUT_FILE}`;
  const definitions = await Bun.file(OUTPUT_FILE).text();
  await Bun.write(
    CONSTANT_FILE,
    `// Generated by scripts/bundle-extension-types.ts. Do not edit.\n// biome-ignore-all lint/suspicious/noTemplateCurlyInString: Type declarations contain literal template placeholders.\nexport const EXTENSION_TYPE_DEFINITIONS = ${JSON.stringify(definitions)};\n`,
  );
  await Bun.$`bunx biome format --write ${CONSTANT_FILE}`;
}

await main();
