import type { ScriptContext } from "swarm-sdk";

// Spike-3 stretch (autopilot): nightly digest over the PM app's own named queries.
// Runs as a swarm-script workflow node (args: { appId, queries?: string[] }); proves
// "agents are end-users of the app they built" — the app surface (app_query) is the
// data API, page_create is the observable sink.
export default async function pmDigest(args: any, ctx: ScriptContext) {
  if (!args?.appId) return { error: "appId is required" };
  const queryNames: string[] = Array.isArray(args.queries) && args.queries.length > 0 ? args.queries : ["inbox"];
  const sections: string[] = [];
  const counts: Record<string, number> = {};
  for (const name of queryNames) {
    const res: any = await ctx.swarm.app_query({ appId: args.appId, query: name });
    const rows: any[] = res?.data?.rows ?? [];
    counts[name] = rows.length;
    const lines = rows
      .slice(0, 15)
      .map((r: any) => {
        const title = r.title ?? r.prompt ?? r.id;
        const status = r.status ?? "";
        const stale = r.stale ? " (stale)" : "";
        return `- ${String(title).slice(0, 120)}${status ? ` — ${status}` : ""}${stale}`;
      })
      .join("\n");
    sections.push(`## ${name} (${rows.length})\n\n${lines || "_empty_"}`);
  }
  const body = `# PM Inbox digest\n\nGenerated by the nightly autopilot workflow.\n\n${sections.join("\n\n")}`;
  const page: any = await ctx.swarm.page_create({
    title: "PM Inbox digest",
    content: body,
    kind: "html",
  });
  return { counts, page: page?.data ?? page };
}
